### ISSUE TITLE
Recognize gem dependencies as rip dependencies

### ISSUE THREAD

**Issue by defunkt** [defunkt/rip#1]

**Comment by jmhodges** [comment]
Working my way through the rubygems codebase to figure out the right places to mock out. I will be [playing music](http://www.youtube.com/watch?v=5LrHfxW4XOg) in celebration when I do.

**Comment by cldwalker** [comment]
Here's a simple version which downloads dependencies: cldwalker@625d2bddc6ba909e603e490bd7444e62add78fc5
It doesn't uninstall dependencies or respect gem versions yet.

**Comment by defunkt** [comment]
@cldwalker - That's awesome! If you can add some tests I'll merge it in so others may build on it?

**Comment by cldwalker** [comment]
Sure. I'll check it out when I get some free time.

**Comment by lazyatom** [comment]
I've added another approach, starting at this commit: [lazyatom@f029c29](http://github.com/lazyatom/rip/commit/f029c292c46698a8f632af8e6397b2d176015c4c)

This is heavily based on cldwalker's work, but refactored to ensure that rip's internal dependency information is kept in sync. Let me know what you think; I'll be trying to use it, and updating accordingly.

**Comment by defunkt** [comment]
This is freaking sweet and this is freaking merged.

**Comment by defunkt** [comment]
So awesome, merged in.
