### ISSUE TITLE
rip-install fails.

### ISSUE THREAD

**Issue by namelessjon** [defunkt/rip#102]
That's about as concise as I can make the issue.  I haven't quite managed to backtrack and figure out how it's all being called yet.

```
$ rip-install merb-core
/home/jon/software/github/rip/lib/rip/parser.rb:12:in `parse': undefined method `map' for "merb-core":String (NoMethodError)
from /home/jon/software/github/rip/lib/rip/parser.rb:4:in `parse'
from /home/jon/software/github/rip/lib/rip/environment.rb:79:in `packages'
from /home/jon/software/github/rip/bin/rip-fetch-dependencies:12:in `fetch_dependencies'
from /home/jon/software/github/rip/bin/rip-fetch-dependencies:27:in `<main>'
```

**Comment by defunkt** [comment]
Are you on master?

```
→ rip install merb-core
fetching merb-core 1.1.0
fetching bundler 0.9.25
fetching abstract 1.0.0
fetching extlib 0.9.14
fetching rspec 1.3.0
installed bundler (0.9.25)
installed abstract (1.0.0)
installed erubis (2.6.5)
installed extlib (0.9.14)
installed mime-types (1.16)
installed camping (2.0)
installed fcgi (0.8.8)
installed memcache-client (1.8.3)
installed cgi_multipart_eof_fix (2.5.0)
installed daemons (1.0.10)
installed fastthread (1.0.7)
installed gem_plugin (0.2.3)
installed mongrel (1.1.5)
installed test-spec (0.10.0)
installed eventmachine (0.12.10)
installed thin (1.2.7)
installed rack (1.1.0)
installed rake (0.8.7)
installed rspec (1.3.0)
installed merb-core (1.1.0)
```

**Comment by namelessjon** [comment]
Yeah.  I'm on master

```
$ git log -n 1
commit 8e6503304e1f4dbb3b437995ed79ddca50f35e01

$ ruby --version
ruby 1.9.1p378 (2010-01-10 revision 26273) [x86_64-linux]
```

And I still get the same error.

**Comment by defunkt** [comment]
Looks like this is a 1.9 issue. I've got 1.9.1p376 and it fails for me too -- I'll look into it.

**Comment by namelessjon** [comment]
In 1.9, strings arn't `Enumerable`

Actually, looking at this a little more, I think it can be solved with a simple `.split()`.  If that works, I'll fork and send a pull request.

**Comment by namelessjon** [comment]
Right, I have a couple of fixes in a couple of branches:

namelessjon/rip@ce38781313a4365bb13defab98a809af55b0c8b4 - this makes `String` `Enumerable` if it isn't already.  A better approach might be to call `Array#split` at appropriate places, but this works.

namelessjon/rip@055207bc026037c391e4257e431c2d4894f23de8 - a fix for the change in `gem list` output for 1.3.7

**Comment by cldwalker** [comment]
This works for me and the fixes have been merged into master. Any reason this is still open?

**Comment by josh** [comment]
closing
