### ISSUE TITLE
rip install --only PACKAGE

### ISSUE THREAD

**Issue by cldwalker** [defunkt/rip#110]
Added the ability to only install a package i.e. without its dependencies. This comes in handy when you don't agree with the package author's dependencies or when installing some of a package's dependencies in another gem manager.

I can change the option name if you'd like. '--only' made sense to me.
Branch: http://github.com/cldwalker/rip/tree/no_deps

Also, I noticed it's not possible to install multiple packages i.e. `rip install ronn repl` because latter arguments are reserved for version. Perhaps we could add support for multiple packages by comma  delimiting them?

**Comment by josh** [comment]
892ec6b94df5abeab703504517e101f38caae705

**Comment by cldwalker** [comment]
I actually left this open to see if installing multiple packages would be a new feature to consider. New ticket?

**Comment by josh** [comment]
i'd say use a deps.rip file to install multiple packages. wana keep installs argv's simple so the second arg could be a version or path
