### ISSUE TITLE
gc bug deleting packages it shouldn't

### ISSUE THREAD

**Issue by cldwalker** [defunkt/rip#115]
I've noticed that rip-gc sometimes deletes packages it shouldn't. I traced it to an error where the installed packages of a ripenv were being appended to previous ripenv packages without a delimiting "\n". Without a "\n",  the last package of the previous ripenv and the first package of the next ripenv are joined together, causing both packages to be deleted. I saw my deleted packages drop from 50 to 39 after this fix.

Branch: http://github.com/cldwalker/rip/tree/gc_bug

Didn't add tests since I didn't see any previous tests for this executable and wasn't sure how to test it.

**Comment by josh** [comment]
defunkt/rip@d506ca1ebeedfb941b561ada2e3b82798438f228
