### ISSUE TITLE
rake install incorrectly copies lib dir

### ISSUE THREAD

**Issue by a1russell** [defunkt/rip#116]
Currently, running rake install doesn't correctly copy the files under the lib directory. All of the files are copied to the libdir, resulting in a flat file structure. Instead, the hierarchy should be retained.

For my fix, see http://github.com/a1russell/rip/commit/9eeb43388b92fee3079d7835143ce912301ae705

**Comment by josh** [comment]
defunkt/rip@bc204d818b6748bce243e8b3d760a5c3d7f776fb

**Comment by a1russell** [comment]
Thanks!
