### ISSUE TITLE
rake man:build doesn't work

### ISSUE THREAD

**Issue by a1russell** [defunkt/rip#117]
Currently, rake man:build errors out.

For my fix, see http://github.com/a1russell/rip/commit/3e9676fcfcaf0818858df023d6493776e8c2ce3e

Alternatively, I think you could just move your *.ronn files into the appropriate directory man1 or man5.

**Comment by defunkt** [comment]
Fixed in f6074e5cd0d7db297fc5cd06c1bfdc8aa5ca3c32, thanks!
