### ISSUE TITLE
more diagnostics messages on error

### ISSUE THREAD

**Issue by timurb** [defunkt/rip#118]
While trying to install something from wrong url rip says nothing:
    $ rip install http://github.com/someuser/somerepo
    $

Obviously I have forgotten to append the .git and when I try to git clone from that url git says where I was wrong:
    $ git clone http://github.com/someuser/somerepo
    fatal: http://github.com/someuser/somerepo/info/refs not found: did you run git update-server-info on the server?
    $

So I can see the mistake and correct it.

**Comment by cldwalker** [comment]
+1

I experienced similar confusion when trying to installing a zipped package `rip install ftp://ftp.ruby-lang.org/pub/ruby/1.8/ruby-1.8.7-p249.zip`, thinking a manpage was accurately describing existing functionality.

Here's a simple fix: http://github.com/cldwalker/rip/tree/install_error

**Comment by josh** [comment]
defunkt/rip@f1d63441474f03efbd0a978eb2a4e05c88f7b170
