### ISSUE TITLE
rip-yard and rip-yri

### ISSUE THREAD

**Issue by cldwalker** [defunkt/rip#119]
I've written some [rip executables](http://github.com/cldwalker/irbfiles/blob/master/boson/commands/public/rip_yard.rb) that interface with [yard](http://github.com/lsegal/yard). Currently they exist as boson commands but I could easily convert them to normal executables. Is there interest in bringing this into rip or should this exist as a rip plugin? Fyi, documentation is lazily generated when rip_yard or rip_yri are called.

**Comment by josh** [comment]
That'd be a great as a plugin. I'd love to use `rip rdoc rack` and have it open the rdoc in my browser or something. Maybe it eventually could be rip core but its easily done as a plugin for now.
