### ISSUE TITLE
rip-package-directory, a local package which doesn't need updating

### ISSUE THREAD

**Issue by cldwalker** [defunkt/rip#120]
I created a package which packages up a directory but never has to be updated since it's actually a symlink to the given directory: http://github.com/cldwalker/rip/tree/directory

My motivation for this is to use current versions of certain local libraries without having to constantly update their rip package counterparts. I achieve this by symlinking ~/.rip/.packages/:name to the given directory. The only downside to this approach is that the given directory ends up having a metadata.rip. This new package type installs and uninstalls cleanly. Like file packages, these packages have no versioning.

Some examples:
     # Can install relative paths
     $ rip install .
     installed boson ()

```
 # Can install full paths
 $ rip install /path/to/project
 installed project ()
```

Is there interest for bringing this into rip? If so, I'll add tests.

**Comment by josh** [comment]
I don't think this behavior belongs. Instead of `rip install /path/to/project`, `export RUBYLIB=/path/to/project/lib:$RUBYLIB`

rip packages should be immutable.
