### ISSUE TITLE
Fix for uninstalling packages with man pages

### ISSUE THREAD

**Issue by cldwalker** [defunkt/rip#121]
I noticed that packages with man pages aren't able to uninstall:

```
$ rip env -c blah
$ rip install git-hub
installed git-hub (1.3.1)

$ rip uninstall git-hub
git-hub (1.3.1) uninstalled

# Uninstalled package still shows up because man pages weren't unlinked 
$ rip list
ripenv: blah

git-hub (1.3.1)
```

Here's a fix for this: http://github.com/cldwalker/rip/tree/uninstall_man
Haven't added tests since I don't see any for this executable and not sure how you'd like to test it.

**Comment by josh** [comment]
Think we should just revert this: defunkt/rip@bf0c446c6908dc425e5eeae22e7985e51c56b4c5

solves the problem right? could use some test coverage in this area

**Comment by cldwalker** [comment]
Reverting does solve this issue. Created new branch which reverts and adds uninstall tests: http://github.com/cldwalker/rip/tree/un2

**Comment by josh** [comment]
defunkt/rip@8e1cdb62e827e9f4ca6310feffcf249868ca5b97
