### ISSUE TITLE
Added rip-ext for managing packages with c extensions across ruby versions

### ISSUE THREAD

**Issue by cldwalker** [defunkt/rip#122]
Branch: http://github.com/cldwalker/rip/tree/ext

rip-ext lets users rebuild packages with c extensions as needed for the current ruby version.

rip-ext can be used manually with your ruby version tool of choice:
    $ rip env -c test
    $ rip install hpricot
    installed hpricot (0.8.2)

```
# switch ruby version, could use any tool here
$ rvm use 1.9.1

# List all packages (across ripenvs) that need to be rebuilt for this ruby version
$ rip ext -l
/Users/bozo/.rip/.packages/hpricot-608cb7a0d59bd080f3a1265fef1bfcfd
# Rebuilds listed packages and symlinks the newly built ones
$ rip ext
Building extensions for hpricot ...
```

Using rvm's hooks, we can use it automatically:
    # Adds a hook to be invoked each time we switch ruby versions
    $ echo "rip ext -i" >> ~/.rvm/hooks/after_use

```
$ rip env -c test2
$ rip install hpricot
installed hpricot (0.8.2)

$ rvm use 1.9.1
info: running hook after_use
1 package(s) have extensions to build for this ruby version.
Proceed? [y]/n
# Entering return or y builds extensions as above
# Entering n, only packages with previously built extensions are symlinked
# Can always build extensions later with `rip ext`
```

Some points on how rip-ext works:
- It reuses as much of rip as possible and thus only ends up causing minor tweaks in rip-build and rip-gc.
- It uses rip-build underneath and thus ruby-version-specific packages are just another package.
- Introduced a relationship between the version-specific package and the originally installed package with a .rip_parent file which points to the original package. We could experiment with other ways. This way seemed the simplest and similar to metadata.rip.

Their are some minor commits to make as indicated with TODO. I also wasn't sure if I should modify rip-uninstall to remove packages for all ruby versions or if we should just leave rip-gc to clean them up.

I can add tests for all this if you want this in rip. Hopefully you do since this makes it easy to use rip for all gems across any ruby version!

One note in trying this command, you'll get warnings for existing packages that have c extensions. To get rid of these warnings, uninstall them, remove their .packages directories and reinstall them.

**Comment by josh** [comment]
defunkt/rip@792d343920877777ab1eb0b3ddd877d14fa0cd08

**Comment by josh** [comment]
Reconsidered your parent pointer idea: #134

**Comment by cldwalker** [comment]
I ended up rebuilding rip-ext using only build.rip: http://github.com/cldwalker/rip/tree/ext2

Instead of storing versions across packages and having parent pointers, I keep all versions of package within a .versions subdirectory. To switch a version, I symlink the package's lib,man,bin and build.rip to the corresponding paths in a versioned package i.e.:
    build.rip  -> .versions/9bbb88008e0beb43d4a0f2fced0b512f/build.rip
    bin  -> .versions/9bbb88008e0beb43d4a0f2fced0b512f/bin
    lib   -> .versions/9bbb88008e0beb43d4a0f2fced0b512f/lib

One major advantage this has over the previous method is that uninstalling a package stays simple. Otherwise, this newer version acts the same as described above.
