### ISSUE TITLE
Fix for rip install nokogiri

### ISSUE THREAD

**Issue by cldwalker** [defunkt/rip#123]
Using rubygems on mac 10.5:
    $ rip install nokogiri -o
    fetching nokogiri 1.4.2.1
    nokogiri 1.4.2.1 not found
    cleaning up /Users/bozo/.rip/.packages/nokogiri-a0f3eb823c6f6adb62ee0106e893abd5

Why did this happen? nokogiri has its latest version specified by platform:
    $ gem list nokogiri --remote
    **\* REMOTE GEMS ***

```
nokogiri (1.4.2.1 x86-mingw32 x86-mswin32, 1.4.2 ruby java, 1.2.3 x86-mswin32-60)
```

Since rip picks up the wrong latest version, `gem fetch` fails inside of rip-package-gem:
    $ gem fetch nokogiri '-v 1.4.2.1'
    ERROR:  Could not find a valid gem 'nokogiri' (= 1.4.2.1), here is why:
          Found nokogiri (1.4.2.1), but was for platforms x86-mswin32 ,x86-mingw32

With this fix, http://github.com/cldwalker/rip/tree/nokogiri, rip detects the correct latest version for nokogiri.
    $ rip install nokogiri -o
    installed nokogiri (1.4.2)

**Comment by josh** [comment]
This edge case belongs under the GemFetcher class since it isn't a problem on rpg.

**Comment by cldwalker** [comment]
Updated branch

**Comment by josh** [comment]
defunkt/rip@f8448319171626163f4754c6684e1fa357dfc442
