### ISSUE TITLE
rip-on and rip-off should check whether inactive/active symlinks exist.

### ISSUE THREAD

**Issue by hlian** [defunkt/rip#126]
Otherwise, calling rip-on or rip-off more than once in a row throws a mv error:

```
$ rip-on
$ rip-on
mv: rename /Users/me/.rip/inactive to /Users/me/.rip/active/inactive: No such file or directory
```

Some example code that could fix this:
http://github.com/hlian/rip/compare/master...rip_on_off_checks
http://github.com/hlian/rip/tree/rip_on_off_checks

**Comment by josh** [comment]
defunkt/rip@2ae48ec10aa52e9046ee63f06caadfbcf35c978e
