### ISSUE TITLE
rip-push hosed

### ISSUE THREAD

**Issue by defunkt** [defunkt/rip#128]
On master:
    → ruby -e 'p $LOAD_PATH'
    ["/Users/chris/Projects/ronn/lib", "/Users/chris/Projects/rip/lib", "/Users/chris/.rip/system/lib", "./lib/", "./test/", "/ruby/ree-1.8.7/lib/ruby/site_ruby/1.8", "/ruby/ree-1.8.7/lib/ruby/site_ruby/1.8/i686-darwin10.3.0", "/ruby/ree-1.8.7/lib/ruby/site_ruby", "/ruby/ree-1.8.7/lib/ruby/vendor_ruby/1.8", "/ruby/ree-1.8.7/lib/ruby/vendor_ruby/1.8/i686-darwin10.3.0", "/ruby/ree-1.8.7/lib/ruby/vendor_ruby", "/ruby/ree-1.8.7/lib/ruby/1.8", "/ruby/ree-1.8.7/lib/ruby/1.8/i686-darwin10.3.0", "."]

On bf0c446c6908dc425e5eeae22e7985e51c56b4c5:

```
→ ruby -e 'p $LOAD_PATH'
["/Users/chris/.rip/active/lib", "/Users/chris/Projects/ronn/lib", "/Users/chris/Projects/rip/lib", "/Users/chris/.rip/system/lib", "./lib/", "./test/", "/ruby/ree-1.8.7/lib/ruby/site_ruby/1.8", "/ruby/ree-1.8.7/lib/ruby/site_ruby/1.8/i686-darwin10.3.0", "/ruby/ree-1.8.7/lib/ruby/site_ruby", "/ruby/ree-1.8.7/lib/ruby/vendor_ruby/1.8", "/ruby/ree-1.8.7/lib/ruby/vendor_ruby/1.8/i686-darwin10.3.0", "/ruby/ree-1.8.7/lib/ruby/vendor_ruby", "/ruby/ree-1.8.7/lib/ruby/1.8", "/ruby/ree-1.8.7/lib/ruby/1.8/i686-darwin10.3.0", "."]
```

Notice that `/Users/chris/.rip/active/lib` is missing from the first paste.

**Comment by josh** [comment]
Just hit the same thing this morning. I'll try to look into it tonight unless you beat me to it.

`rip-push` is growing into a nasty hack. It was a fine shell hack in the beginning, but I think its time we formalize it into rip. wdyt about a `RIPENVS`, `RIPSUBENVS`, environment variable to properly track pushed rip environment names?

**Comment by cldwalker** [comment]
It seems to stop working after a53ad99c34c55bbfa174173bac030509a9fede49. This commit modifies ENV['RIPENV'] which affects clean_env_path and thus all rip-config actions

**Comment by josh** [comment]
defunkt/rip@4556bf4bda61394a2bfca2afb29692bd4235a034
