### ISSUE TITLE
rip install rails --pre

### ISSUE THREAD

**Issue by cldwalker** [defunkt/rip#136]
Added preliminary support for --pre: http://github.com/cldwalker/rip/tree/pre
- This flag only supports the latest release. This limitation occurs because rip uses `gem fetch` to download gems and that command doesn't allow for specifying prerelease versions i.e. `gem fetch activerecord '-v 3.0.0.rc'`.
- rpg doesn't support prereleases yet. Not sure if rip should explicitly warn about that.

Unfortunately this flag doesn't work with rails yet since prelease activesupport conflicts with a 2.3.8 activesupport coming from mail. Not sure how to solve this as it seems rip should be aware it's dealing with a rails release gem even when it's looking at mail's dependencies. Or perhaps this could just be patched with rip-repair? Any thoughts on making this work?

**Comment by josh** [comment]
You should have to specify the full version if you want to download rc stuff.

  `rip package activerecord 3.0.0.rc`

Plus that pre flag isn't going to work in a ripfile (nor do we really want it too)
