### ISSUE TITLE
Recognize "ambition-1.0.0" as "ambition version 1.0.0" when installing from directories

### ISSUE THREAD

**Issue by defunkt** [defunkt/rip#2]

**Comment by nakajima** [comment]
I can take this one if nobody has any objections.

**Comment by defunkt** [comment]
Go for it!

**Comment by nakajima** [comment]
Submitted for your approval:

https://github.com/nakajima/rip/commit/4cc3c7a948cbc7c9a7fe80d311b6f1ec0f92a43f

Do we want to also recognize things like "ambition-1" and "ambition-2" as versions 1 and 2 respectively? It seems a bit sketchy, but I thought I'd mention it anyway.

**Comment by defunkt** [comment]
Sweet, merged in.

Maybe the capture should be `-(\d+.)+` ?

**Comment by nakajima** [comment]
I updated the capture:

https://github.com/nakajima/rip/commit/83080eb33bb6717f26bcd483193bdc00f0935df3

**Comment by defunkt** [comment]
Awesomeness. Closing.
