### ISSUE TITLE
rip gem installation issue

### ISSUE THREAD

**Issue by technoweenie** [defunkt/rip#21]
Got this trying to install rip with rubygems 1.3.4

<pre><code>
$ sudo gem install rip    
Building native extensions.  This could take a while...
ERROR:  Error installing rip:
    ERROR: Failed to build gem native extension.

/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby extconf.rb
rip: installing library files
rip: installing rip binary
rip: setting up ripenv
rip: please create one of these startup scripts in $HOME:
/Library/Ruby/Gems/1.8/gems/rip-0.0.1/lib/rip/setup.rb:91:in `setup_startup_script': undefined local variable or method `startup_scripts' for main:Object (NameError)
    from /Library/Ruby/Gems/1.8/gems/rip-0.0.1/lib/rip/setup.rb:38:in `install'
    from /Library/Ruby/Gems/1.8/gems/rip-0.0.1/ext/../setup.rb:26
    from extconf.rb:11:in `require'
    from extconf.rb:11
</code></pre>

**Comment by technoweenie** [comment]
fix: http://github.com/technoweenie/rip/commit/6530d5e55dd1ff5110ae44081b1528132e437e2b

**Comment by defunkt** [comment]
Merged, thanks!
