### ISSUE TITLE
Remove need to source profile or start a new console

### ISSUE THREAD

**Issue by aeden** [defunkt/rip#22]
Error:

RIPDIR env variable not found. did you run setup.rb?

There must be a way to set the RIPDIR environment variable in the current console session. Maybe a system command?

**Comment by joefiorini** [comment]
Could we drop "export RIPDIR=~/.rip" in the install script?

**Comment by defunkt** [comment]
There's not.

Please re-open if I'm wrong.

**Comment by joefiorini** [comment]
What's wrong with calling ENV["RIPDIR"] = RIPDIR after setup appends to the bash script? Curious why that wouldn't work?

**Comment by defunkt** [comment]
Try it. It does not work.

This is a feature of Unix. Subprocesses have no access to the parent process's environment.
