### ISSUE TITLE
Do Not Modify ~/.{bash,zsh,...}rc in Gem Installation

### ISSUE THREAD

**Issue by rue** [defunkt/rip#23]
Installation through Gems (at least) directly modifies ~/.bashrc and environment, which is pretty questionable. Would it be acceptable to change the default to not make modifications, but provide a `rip setup` command that does it if so desired?

**Comment by rue** [comment]
Writing a patch...there is also some use of the rc file's contents rather than just checking the env which seems silly, is there a reason?

**Comment by defunkt** [comment]
The main reason for this is I don't want Rubygems to install the `rip` binary because then every time you run `rip` it'll load the Rubygems runtime.

Perhaps we should install, as you suggest, a simple `rip-setup` script through Rubygems that does what it needs to do.

**Comment by defunkt** [comment]
As far as checking `ENV['blah']`, that's a great idea.

**Comment by rue** [comment]
Is this version workable?

http://github.com/rue/rip/commit/46bac5fca0ca7fadef620ee6b87e48f9d5c2f59b

**Comment by collin** [comment]
installed with Rue's "rip setup" and got an "all systems go" :)

**Comment by rue** [comment]
Closed by 90ff5837d1aeda2d26f3a1e1b52493fd37b83feb
