### ISSUE TITLE
Install error (via gems) on Mac OS X 10.5

### ISSUE THREAD

**Issue by rubaidh** [defunkt/rip#24]
I've (hopefully) attached the transcript of the error:

```
mathie@Tullibardine ~ (master) $ sudo gem install rip
[mathie@Tullibardine -> root] Password:
Building native extensions.  This could take a while...
ERROR:  Error installing rip:
    ERROR: Failed to build gem native extension.

/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby extconf.rb
rip: installing library files
rip: installing rip binary
rip: setting up ripenv
rip: please create one of these startup scripts in $HOME:
/Library/Ruby/Gems/1.8/gems/rip-0.0.1/lib/rip/setup.rb:91:in `setup_startup_script': undefined local variable or method `startup_scripts' for main:Object (NameError)
    from /Library/Ruby/Gems/1.8/gems/rip-0.0.1/lib/rip/setup.rb:38:in `install'
    from /Library/Ruby/Gems/1.8/gems/rip-0.0.1/ext/../setup.rb:26
    from extconf.rb:11:in `require'
    from extconf.rb:11


Gem files will remain installed in /Library/Ruby/Gems/1.8/gems/rip-0.0.1 for inspection.
Results logged to /Library/Ruby/Gems/1.8/gems/rip-0.0.1/ext/gem_make.out
mathie@Tullibardine ~ (master) $ rip
RIPDIR env variable not found. did you run setup.rb?
```

I'm on Mac OS X 10.5.7, with the native Ruby.  Not sure what else you need?

**Comment by mathie** [comment]
... and I totally meant to submit that as me, not @rubaidh!

At a guess, my ~/.bashblah isn't ... conventional?

**Comment by lucky** [comment]
For clarity, this doesn't affect macports ruby 1.8.7.

**Comment by lucky** [comment]
@mathie: dump the contents of /Library/Ruby/Gems/1.8/gems/rip-0.0.1/ext/gem_make.out here, please.

**Comment by rue** [comment]
This should be fixed by b13f3685bd65, can you verify?

**Comment by kwhinnery** [comment]
I am still getting this error on my system as well

**Comment by martinstreicher** [comment]
I installed rip today on my Mac OS X machine. Version is 10.5.7. Xcode is the latest version as of today. Ruby and gem were my own builds. I also ran the /usr/bin versions of Ruby and gem and had no problems.

**Comment by mathie** [comment]
Umm, I suck. I failed to verify this before, err, installing a more recent version of Mac OS X on my laptop.  FWIW, it installs correctly on a, err, more recent version of Mac OS X. :-)

**Comment by defunkt** [comment]
Sweet, thanks.
