### ISSUE TITLE
root privileges shouldn't be required for installation

### ISSUE THREAD

**Issue by brett** [defunkt/rip#26]
'nuff said

**Comment by defunkt** [comment]
If anyone wants to take a stab at this I'd accept the patch.

**Comment by rue** [comment]
This is addressed by [rue/rip/commits/ac20d025](http://github.com/rue/rip/commits/ac20d0258f1d3d0cd4e83af79ae6d217bc71affc), revised from earlier version.

**Comment by brett** [comment]
sorta...having a namespaced standard like rubygems has, including provisions for multiple ruby versions seems like it would make more sense than adhoc installs. especially true for package maintainers (macports, apt, pkg, etc)
