### ISSUE TITLE
error on /usr/local/bin/rip does not exist

### ISSUE THREAD

**Issue by seand** [defunkt/rip#27]
$ sudo gem install rip
Building native extensions.  This could take a while...
ERROR:  Error installing rip:
    ERROR: Failed to build gem native extension.

/opt/local/bin/ruby extconf.rb install rip
rip: installing library files
rip: installing rip binary
rip: something failed, rolling back...
/opt/local/lib/ruby/1.8/fileutils.rb:1262:in `initialize': No such file or directory - /usr/local/bin/rip (Errno::ENOENT)

problem solved by making /usr/local/bin which apparently did not yet exist.

**Comment by defunkt** [comment]
What's your OS?

**Comment by seand** [comment]
osx 10.5.7

no problems whatsoever on debian etch

**Comment by defunkt** [comment]
Did you have `/usr/local/bin` in your `$PATH` prior to creating it?

**Comment by steveh** [comment]
Same issue, Mac OS X 10.5.7 Macports Ruby 1.8.7.

Tried removing /usr/local/bin from my $PATH, did not work
Created /usr/local/bin, worked

$PATH =
/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:/Users/steve/.home/bin

**Comment by defunkt** [comment]
Okay, we're using `/usr/bin` by default now as of ab5e4c8b1.
