### ISSUE TITLE
`rip server`

### ISSUE THREAD

**Issue by nakajima** [defunkt/rip#28]
Where's the doc?

I'll take this one. Can't tag myself with it anymore it seems though.

**Comment by nakajima** [comment]
Plugin?

**Comment by nakajima** [comment]
Getting started: http://github.com/nakajima/rip-server

**Comment by mtodd** [comment]
I've done a tiny bit of hacking on nakajima's code, found at http://github.com/mtodd/rip-server

Now can dynamically generate (though with shitty RDoc options) and display the RDoc files.

Was thinking of supporting a doc.rip file (similar to deps.rip) which would provide options to the RDoc generator (at the very least).

Thoughts?

**Comment by mtodd** [comment]
Also, do we want to have this server be something akin to a gem mirror for rip? As in, provide some way to make your local machine be able to be installed from (maybe even as simple as running git server or something)?
