### ISSUE TITLE
/usr/local/bin/rip is not removed when rip gem is uninstalled

### ISSUE THREAD

**Issue by wwood** [defunkt/rip#29]

**Comment by defunkt** [comment]
This should be solved by adding a `rip setup uninstall` command that removes Rip by running `Rip::Setup.uninstall`.

`/usr/local/bin/rip` is not the only file Rip installs and therefor needs to remove.

**Comment by defunkt** [comment]
We've added `rip uninstall rip` as the defacto way to uninstall rip moving forward.
