### ISSUE TITLE
Add sources

### ISSUE THREAD

**Issue by defunkt** [defunkt/rip#3]
If you type `rip install ambition` and nothing is found, try searching the Sources e.g. github, rubyforge, gemcutter.

Sources should be installable as plugins.

**Comment by defunkt** [comment]
Basic support was added for this tonight in the form of `RemoteGemPackage`.

You can now `rip install ambition`.

**Comment by lazyatom** [comment]
I think this is now covered, either by the source list in your current master, or by my branch which defaults to whatever sources the user already has for gems.
