### ISSUE TITLE
depending on the main Rakefile for C extensions is bad (rip should support extconf.rb)

### ISSUE THREAD

**Issue by tenderlove** [defunkt/rip#30]
For most of my C extensions, the Rakefile depends on having development dependencies installed.  In fact, the only tasks that should be executed in the Rakefile should be during development mode.  This means that if anyone wants to install my C extension via rip, they must have all development dependencies installed as well.

There needs to be a way to tell rip what to do when installing C extensions.  With RubyGems, I can give the gemspec a specific extconf.rb _or_ specific Rakefile that does not have any development dependencies, but knows how to build my extension.

**Comment by defunkt** [comment]
`rip build` is the attempt to do what you describe.

http://github.com/defunkt/rip/blob/90ff5837d1aeda2d26f3a1e1b52493fd37b83feb/lib/rip/commands/build.rb

**Comment by tenderlove** [comment]
woot!  thank you very much
