### ISSUE TITLE
Don't say 'Could not find the command: --help' on rip --help

### ISSUE THREAD

**Issue by rtomayko** [defunkt/rip#31]
Just show the help output.

http://github.com/rtomayko/rip/commit/help

**Comment by ghost** [comment]
I got the same results by re-working Rip::Commands.parse_args [my solution treats -h and --help as options[:h] and options[:help], which seems more intuitive but may well break something :) ]

http://gist.github.com/129239

**Comment by rtomayko** [comment]
I like that better. Seems cleaner and more correct to me.

**Comment by ghost** [comment]
Thanks - I thought so too. Didn't have time to write a test, but it works for me.

**Comment by defunkt** [comment]
Alright, merged in Ryan's patch then James'. Thanks guys.
