### ISSUE TITLE
nil object when running rip install test/dev.rip

### ISSUE THREAD

**Issue by denisdefreyne** [defunkt/rip#33]
Right after installing rip (with `ruby setup.rb`), `rip install test/dev.rip` fails:

```
▸ rip install test/dev.ripundefined method `exists?' for nil:NilClass
rip: install failed
-> undefined method `exists?' for nil:NilClass
```

… but passing `--trace` somehow makes it work:

```
▸ rip install test/dev.rip --trace
Successfully installed test-spec-mini.rb (2009-06-13)
Successfully installed fakefs (c6d4b3f)
```

This happens with edge rip on Ruby 1.8.7.

**Comment by defunkt** [comment]
don't memoize actual_package in HTTPPackage. closed by 2ce50a8f1209bc271c75984b066591ea86756221
