### ISSUE TITLE
Publish Package URL Convention For SCMs (hg+http:// etc.?)

### ISSUE THREAD

**Issue by rue** [defunkt/rip#34]
Since some SCMs do not provide any clues to their identity in the URL alone, pip's example of `scm+proto` (e.g. `hg+http`, `cvs+ssh` etc.) is probably the simplest way to handle the situation (another suggested method is a --vcs flag, but it seems substandard, in particular because the full URL can be distributed as a single unit (URL schemes may contain +, in case someone is wondering.))

Whichever mechanism chosen, it should be prominently publicised in the API and docs to avoid issues with adoption and Packages for the various other SCMs. (That is, I did not see a mention of this when I was looking.)

**Comment by defunkt** [comment]
Good idea.

I'm fine just doing what Pip does.

**Comment by jmhodges** [comment]
Yeah, this seems appropriate. Extensible to rubygems etc. if need be.

**Comment by timshadel** [comment]
I found a link to the Pip scm url docs (for reference).

http://pip.openplans.org/requirement-format.html#version-control
