### ISSUE TITLE
Installation form gem gives 404 response.

### ISSUE THREAD

**Issue by tobi** [defunkt/rip#35]
~/Code/Ruby/liquid/benchmark/fixtures (master) $ sudo gem install rip
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found 404 (http://rubyforge.iasi.roedu.net/gems/rip-0.0.1.gem)
~/Code/Ruby/liquid/benchmark/fixtures (master) $ sudo gem install rip
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found 404 (http://rubyforge.iasi.roedu.net/gems/rip-0.0.1.gem)
~/Code/Ruby/liquid/benchmark/fixtures (master) $ sudo gem install rip
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found 404 (http://gems.rubyforge.mmmultiworks.com/gems/rip-0.0.1.gem)

**Comment by Wijnand** [comment]
I can confirm this.

**Comment by amerine** [comment]
Strange, its not even on http://master.mirror.rubyforge.org/gems/ I wonder what's up.

**Comment by amerine** [comment]
This is affecting more then just rip. Almost all rubyforge mirrors are screwed up atm.

**Comment by defunkt** [comment]
Looks like it was a Rubyforge fluke.
