### ISSUE TITLE
Installing from gem requires root access

### ISSUE THREAD

**Issue by rkh** [defunkt/rip#39]
I have all my ruby stuff inside /opt/ruby, which is owned by a normal user account, not by root.
Still I get:

  rip: access denied. please try running again with `sudo`

I do not want to install gems as root and I don't think you should force people to do so.

**Comment by devyn** [comment]
Maybe have it check whether the user has permissions to use the Dir, before telling them they have to.

**Comment by rue** [comment]
The merged commits should now let you define the install dirs, the gem and rake used etc. Can you check if this solves the issue?

**Comment by rkh** [comment]
Works fine now, thanks.
