### ISSUE TITLE
rip env share ENV

### ISSUE THREAD

**Issue by defunkt** [defunkt/rip#4]
Should produce a .rip file of all the libraries (and their versions) in a ripenv

**Comment by jmhodges** [comment]
So this is predicated on the idea that we keep the list of which versions we have installed somewhere or have some way of easily reproducing that list. I'm ka-thunking on the best way of doing that. 

One idea is just have the .rip file updated on every install and uninstall. I think that's probably what I'm going to go with but I want to sleep on it.

**Comment by defunkt** [comment]
We already keep and update the versions.

**Comment by defunkt** [comment]
https://github.com/defunkt/rip/blob/69daedab81e0715378853372a67e3a12320e7624/lib/rip/package_manager.rb#L40-42

**Comment by defunkt** [comment]
Doh, this is already done:

`rip freeze ENV`

**Comment by jmhodges** [comment]
Way to go, us.
