### ISSUE TITLE
Rip doesn't install in JRuby

### ISSUE THREAD

**Issue by codahale** [defunkt/rip#41]
But good news -- it's not your fault: http://jira.codehaus.org/browse/JRUBY-3761

There may be a work-around for this, though.

**Comment by pjhyett** [comment]
Ha, I opened a ticket for this a few months back, but didn't include a test case so they closed it. Thanks for following through.

**Comment by codahale** [comment]
Nick Sieger just fixed JRUBY-3761 with d1ae677, which should be in JRuby 1.4.
