### ISSUE TITLE
Dependencies not loaded (MIME::Type example from http://hellorip.com/about.html).

### ISSUE THREAD

**Issue by krukow** [defunkt/rip#42]
Running the example from http://hellorip.com/about.html
on MacOSX fails to load dependency mime-types (>= 0) (Gem::LoadError)

shelltrace
krukow:~$ ruby -v
ruby 1.8.6 (2008-08-11 patchlevel 287) [i686-darwin9.4.0]

krukow:~$ rip list
ripenv: base

nothing installed
krukow:~$ ruby -r grit -e "puts Grit"
ruby: no such file to load -- grit (LoadError)
krukow:~$ rip install git://github.com/defunkt/grit.git v1.1.1b
running install hook for diff-lcs
Successfully installed diff-lcs (491fbc0)
running install hook for mime-types
Successfully installed mime-types (v1.16)
running install hook for grit
Successfully installed grit (v1.1.1b)
krukow:~$ rip list
ripenv: base

diff-lcs (491fbc0)
grit (v1.1.1b)
mime-types (v1.16)
krukow:~$ ruby -r grit -e 'puts Grit'
/opt/local/lib/ruby/site_ruby/1.8/rubygems.rb:636:in `report_activate_error': Could not find RubyGem mime-types (>= 0) (Gem::LoadError)
    from /opt/local/lib/ruby/site_ruby/1.8/rubygems.rb:141:in`activate'
    from /opt/local/lib/ruby/site_ruby/1.8/rubygems.rb:49:in `gem'
    from /Users/krukow/.rip/active/lib/grit.rb:20

**Comment by defunkt** [comment]
This was because my version of Grit was loading RubyGems. I've pushed a fix, sorry about that.
