### ISSUE TITLE
Inferring versions for FilePackage and DirPackage doesn't permit version conflicts

### ISSUE THREAD

**Issue by nakajima** [defunkt/rip#43]
The versions are part of the filenames, but we also derive the package name from the filenames. As a result, packages with inferred versions will never see conflict errors. 

Also, do we want to be installing `foo-1.2.3.rb` into the libpath, or just `foo.rb`, leaving the version out? I think I'd prefer the latter, since requiring `foo.rb` is nicer, though it seems a bit dangerous.

If we want to strip the version from the names, I have a patch here: nakajima/rip@4227a96f5686ad47f444936505105dc1dd526cde

Otherwise, we may want to rethink this feature.

**Comment by defunkt** [comment]
This should be solved in the upcoming Rip 2. Thanks!
