### ISSUE TITLE
Additional Build Options for rip build

### ISSUE THREAD

**Issue by mtodd** [defunkt/rip#46]
I was trying to build my version of the GeoIP lib (found at http://github.com/mtodd/geoip) which requires I provide additional build options. I usually build like so:

env ARCHFLAGS="-arch i386" make --with-GeoIP-dir=/opt/GeoIP/

and installing the gem is like:

sudo env ARCHFLAGS="-arch i386" gem install mtodd-geoip -s http://gems.github.com/ -- --with-GeoIP-dir=/opt/GeoIP/

Unfortunately, I was not able to pass in the additional --with-GeoIP-dir option when running rip build.

This needs to be either documented or support added. I did not look into the current state of its support.

**Comment by defunkt** [comment]
Were you trying to install this as a gem or as a Git package, e.g. `rip install git://github.com/mtodd/geoip.git` ?

**Comment by mtodd** [comment]
I'm almost 100% sure I used:

@rip install git://github.com/mtodd/geoip.git@

but it's been some time and I can't recall exactly. I'll update my Rip install and try again later today.

**Comment by defunkt** [comment]
`rip install` automatically runs `rip build` now, but it doesn't pass along any flags. If that's what you need I'll add it, tho - I just need a testbed and the flags to pass.

**Comment by mtodd** [comment]
Unfortunately, building the GeoIP library isn't exactly trivial; if you look at the README at http://github.com/mtodd/geoip you'll see that you also need to build and install the C GeoIP library before building the library, but it gives you step-by-step directions.

Let me know if I can help or if you need me to test something.
