### ISSUE TITLE
Simplify Rip Extension Development

### ISSUE THREAD

**Issue by mtodd** [defunkt/rip#48]
While working on the rip-server rip extension, it wasn't exactly trivial to continuously modify the code and have it apply to the current rip installation.

Perhaps this could be made more simple, such as a CLI option to require a directory specified?

**Comment by defunkt** [comment]
What do you envision the API for this as looking like?

**Comment by defunkt** [comment]
FYI, you can just put the file somewhere in `~/.rip` and modify it from there. I do that often for both Rip packages and Rubygems.
