### ISSUE TITLE
Allow installation of a specific version of a RemoteGemPackage

### ISSUE THREAD

**Issue by steveh** [defunkt/rip#50]

**Comment by lazyatom** [comment]
I believe I've fixed this in [lazyatom@910a61bf](http://github.com/lazyatom/rip/commit/910a61bf8c3fc8dca8fd4db5bbf74f4d76d3d164); you should now be able to supply versions on the command line, or in deps.rip.

**Comment by lazyatom** [comment]
I've implemented this in a better way in [lazyatom@f7c08fb02](http://github.com/lazyatom/rip/tree/f7c08fb02749336280619fd735760c2f8d7ca8f2), which is based off the more recent defunkt/master

**Comment by defunkt** [comment]
Merged!
