### ISSUE TITLE
Dependencies are not installed for gem packages

### ISSUE THREAD

**Issue by uzytkownik** [defunkt/rip#51]
<pre>% rip install merb 1.0.10 
running install hook for merb
Successfully installed merb (1.0.11)
% rip list
ripenv: merbglobal-ruby18

merb (1.0.11)
</pre>

There is no merb-core & co.

**Comment by mloughran** [comment]
This is a duplicate of issue #1

**Comment by defunkt** [comment]
Closing dupe
