### ISSUE TITLE
Programatically specify rip environment without symlinking

### ISSUE THREAD

**Issue by mloughran** [defunkt/rip#54]
I might be missing it, but I don't see a nice way to programatically specify an environment in the code. I first assumed that `Rip::Env.use('env')` would achieve what I wanted, but that creates a symlink to active...

This is a simplified version of what I'm thinking:

```
require 'rip'
Rip.use_env('foo')

class Rip
  def self.use_env(env)
    $:.unshift(File.expand_path(File.join('~', '.rip', env, 'lib')))
  end
end
```

Does this fit?

**Comment by defunkt** [comment]
You can accomplish this with the `rip ruby` command.

`rip ruby ENV file.rb`

**Comment by mloughran** [comment]
That's certainly useful, but I was more thinking of scenarios where you don't invoke ruby directly. For example passenger `config.ru` files.

**Comment by defunkt** [comment]
If someone creates a patch for this I'll look at it. It's not something I would use yet.

**Comment by defunkt** [comment]
It might be best added as a plugin to start.
