### ISSUE TITLE
Something strange

### ISSUE THREAD

**Issue by teamon** [defunkt/rip#57]
I was playing with envs and thats what i got:

```
teamon:~/Projekty/lib/fakefs (master*) % rip install .
fakefs (unversioned) already installed

teamon:~/Projekty/lib/fakefs (master*) % rip list
ripenv: base

nothing installed

teamon:~/Projekty/lib/fakefs (master*) % rip install git://github.com/nakajima/rip-server.git
(....)

teamon:~/Projekty/lib/fakefs (master*) % rip list
rip: plugin not loaded (/Users/teamon/.rip/active/lib/rip/commands/app.rb)
-> no such file to load -- rack

ripenv: base

nil
nil
rip-server (864e87b)
nil
nil
nil
sinatra (8c666fb)
nil
```

Of course I`m not talking about the "rack not found" but the "rip list" output.

**Comment by defunkt** [comment]
What version of Rip are you using?

I get something similar:

<pre>
→ rip list
rip: plugin not loaded (/Users/chris/.rip/active/lib/rip/commands/app.rb)
-> no such file to load -- rack

ripenv: nak

rip-server (864e87b)
sinatra (8c666fb)
</pre>
