### ISSUE TITLE
Dealing with gems from source and gh

### ISSUE THREAD

**Issue by teamon** [defunkt/rip#58]
When installing gem from source (e.g. merb-flash) and then the same gem from gh (teamon-merb-flash) first, lib/merb-flash.rb gets replaced and then when deleting merb-flash (leaving teamon-merb-flash) there is no merb-flash.rb anymore, so require wont work.

(I think gist will explain it better) 

http://gist.github.com/151879

**Comment by defunkt** [comment]
I noticed this too. What should Rip do if you are trying to override files it already knows about?

The install should fail, right?

**Comment by lazyatom** [comment]
I commited some stuff that might help with this in [lazyatom@a2aefb3](http://github.com/lazyatom/rip/commit/a2aefb3c5b3fa077a8b814e5fd28d5b8abc849b0). 

Presumably when installing a package, if any path in the files list already exists in an install package's files, we can raise an error, right?

**Comment by lazyatom** [comment]
OK, here's a quick attempt: [lazyatom@14f75b923](http://github.com/lazyatom/rip/commit/14f75b923a7837d68e7639e5e8d7129739a81742). I've pasted some sample output [in this gist](http://gist.github.com/168670).

The only problem I can see is that I do still want to be able to play around with monk (in this case), so it should be possible to overcome this somehow. I think this is only really going to be an issue with github vs. normal gems, where the source name is different but the package is basically the same...

**Comment by defunkt** [comment]
I'm not sure this works:

http://gist.github.com/168928

**Comment by lazyatom** [comment]
Hmm, I can't replicate that - here's what I get: http://gist.github.com/169000

I have been testing the gem stuff by blowing away `~/.rip/rip-packages`, but in this instance I tried to follow your failing scenario exactly. Any ideas as to what's different?

I've included a minor diff (that I've since pushed) in the gist, but I don't think that would make a difference...

**Comment by defunkt** [comment]
Okay the newest changes leave me in a better state: http://gist.github.com/169197

But should the whole install fail, or just the install of the conflicting package? I guess this way makes sense.

**Comment by defunkt** [comment]
Okay merged, awesomeness.

**Comment by lazyatom** [comment]
Yeah, it's tricky. I'm really not sure what state is most useful for the user in the end :-/

**Comment by defunkt** [comment]
At first the current behavior surprised me, but it makes the most sense: it's the fault of the gem author, not me. By not rolling back _everything_ you give me (the Rip user) the power to fix the mistake.
