### ISSUE TITLE
man page

### ISSUE THREAD

**Issue by sr** [defunkt/rip#60]
I've started to convert the doc from the gh-pages branch into a man page for fun's sake and to learn about how man pages are made. sr@e475ed97b65969481bcb81b692bb07d2f8eba5e0

**Comment by defunkt** [comment]
Can we have this installed when Rip is installed? Or have `man` detect it somehow?

**Comment by sr** [comment]
`cp rip.1 /usr/share/man/man1` but I wouldn't recommend it since it is very incomplete

**Comment by sunaku** [comment]
@defunkt If Rip extracted the `man/` directories from packages and also set the $MANPATH environment variable, then yes `man` can know about them!  Note that a package's `man/` directory must follow FHS to work correctly, for example:

```
man/
└── man1/
    └── THE_PACKAGE_NAME.1
```
