### ISSUE TITLE
Tab Completion?

### ISSUE THREAD

**Issue by nakajima** [defunkt/rip#61]
A half or maybe all the way drunken implementation of tab completion: http://github.com/defunkt/rip/commit/c42b66a8c79e6065d917e4e992063c2737973c2c

You need to add `complete -o default -o nospace -C "$HOME/git/forks/rip/tools/completions" rip` to your bash profile somewhere to make it work.

If only I knew anything about tree data structures.. I'm sort of looking for help here. Also, implementing it in Ruby makes it hella-slow.

**Comment by sr** [comment]
I meant to look into comletion for zsh too :) but first, I'd like to change the rip commands as they're not as good as they could be, IMO. I am thinking of something less-chatty, probably more git-y. I'll probably start with a quick wrapper on top of `rip` to illustrate my point. BTW, you might want to have a look at http://github.com/drnic/tabtab
