### ISSUE TITLE
Integration test for git package and support for installing a git ref

### ISSUE THREAD

**Issue by sr** [defunkt/rip#62]
http://github.com/sr/rip/tree/git

I initially started to write acceptance test in Ruby, but then I figured that wasn't integration-y enough so I wrote some more unusual tests, inspired by git's test suite. In my opinion, that kind of test are easier to write, much closer to reality and in fact, better. Also, it was fun to write them :)

While I was there, I also implemented support for `rip install git://example.org/repo ref` where ref can be a sha1, a tag, a branch of a full git ref (refs/heads/foo). (I am not happy with the code, though)

BTW, for better output, run the test like this: `./t/test-git | ./t/knock/kn-sum`
If you like those test, I'll add a Makefile or something (with xargs -P to speed up the test?) to ease the process of running the tests.

**Comment by defunkt** [comment]
This should be solved in the upcoming Rip 2. Thanks!
