### ISSUE TITLE
non-root gem installation still broken

### ISSUE THREAD

**Issue by brett** [defunkt/rip#64]
[user@machine]:~% gem install rip
WARNING:  Installing to ~/.gem since /opt/local/lib/ruby/gems/1.8 and
      /opt/local/bin aren't both writable.
Building native extensions.  This could take a while...
ERROR:  Error installing rip:
    ERROR: Failed to build gem native extension.

/opt/local/bin/ruby extconf.rb
rip: installing library files
rip: access denied. please try running again with `sudo`

Gem files will remain installed in /Users/user/.gem/ruby/1.8/gems/rip-0.0.3 for inspection.
Results logged to /Users/user/.gem/ruby/1.8/gems/rip-0.0.3/ext/gem_make.out

**Comment by defunkt** [comment]
You can pass `--bindir` `--libdir` and `--ripdir` to the gem installation process to choose what paths you'd like it installed to.

Can you give it a shot and let me know if it works?

**Comment by wolverian** [comment]
After running `gem install rip -- --build-flags --bindir=$PREFIX/bin --libdir=$PREFIX/lib/ruby --ripdir=$PREFIX/lib/rip`:

```
wolverian@pupupu:~$ rip check
no rip in /usr/bin
```

(PREFIX is $HOME/.local)

**Comment by defunkt** [comment]
This should be fixed in the forthcoming rip 2. Watch this space for the gem. Thanks!

**Comment by brett** [comment]
awesome

**Comment by wolverian** [comment]
defunkt: Watching!
