### ISSUE TITLE
Installing gem should not set up ripenv

### ISSUE THREAD

**Issue by stesla** [defunkt/rip#65]
If I am installing the rip gem, it should not attempt to set up a ripenv. 

Specifically, if I am attempting to install rip using something like Chef, I should not have to create a user-specific shell configuration file for the user I am running Chef as just so that I can install the rip gem.

While I understand that rip creates per-user virtual environments, that behavior is _not_ typical of a gem and rather unexpected.

**Comment by defunkt** [comment]
Rip is not a RubyGem. Rip uses RubyGems to bootstrap its installation.

`gem uninstall rip` will _not_ uninstall Rip. You must use `rip uninstall rip`.

That said, we could add a `--no-ripenv` option to the installation so that Rip only installs its own files. Do you think that would work?

**Comment by stesla** [comment]
Sure. It might also be beneficial to note in the documentation that Rip is just using the gem system to bootstrap itself. I came away from reading the README and quickstart thinking that it was just a normal gem.

**Comment by defunkt** [comment]
This should be solved in the upcoming Rip 2. Thanks!
