### ISSUE TITLE
Intermittent install issue

### ISSUE THREAD

**Issue by tgnj** [defunkt/rip#66]
1st attempt install cucumber

rip install cucumber
Searching gems.github.com for cucumber...
ERROR:  Could not find cucumber in any repository
Searching gems.rubyforge.org for cucumber...
rip: install failed
-> undefined method `name' for nil:NilClass

but if I retry, it would pass.

**Comment by lazyatom** [comment]
I _think_ this might be the gem server not responding withing 5 seconds (which is the internal timeout used), but I'm not sure...

**Comment by tgnj** [comment]
Initially, I thought so too. But the weird thing is that, when I retry - it says gem x installed successfully. It might not be a big deal since it has always worked on the second try.

**Comment by lazyatom** [comment]
Just for interest, the next time it fails, take a look at what's in your ~/.rip/rip-packages directory. How much was successfully downloaded? Typically with a gem, you end up with three similarly-named files - a directory with a .gem in it, then a .gem file, and then a directory containing the unpacked gem.

When it fails, has all of that been created?

**Comment by defunkt** [comment]
This should be fixed with lazyatom's timeout changes. Cheers.

**Comment by tgnj** [comment]
I just did a test port of all gems to rip and it worked awesome. Great job gang.
