### ISSUE TITLE
rip install deps.rip twice both does and does not install deps.rip

### ISSUE THREAD

**Issue by jmhodges** [defunkt/rip#69]
```
→  rip install deps.rip 
Successfully installed sinatra (3b992ad)
Successfully installed haml (2.2.2)

→ echo 'hoe' >> deps.rip

→ rip install deps.rip # And these are the problem areas.
deps.rip already installed

→  rip uninstall deps.rip 
rip: deps.rip isn't installed.
```

These last two lines are the problem, natch.

**Comment by jmhodges** [comment]
This is as of 4c2e0a8f7fe20960fc01932ac9dea1dd0aaa6aa3 (defunkt/master).

**Comment by lazyatom** [comment]
I hope this isn't because of the changes to `PackageManager#add_package` that I made for gems... hmm.

**Comment by defunkt** [comment]
MetaPackages should not be passed to `#add_package` - why do remote gems need to? Is there another way to accomplish what they need?

**Comment by lazyatom** [comment]
I think every package gets passed to `#add_package` - there doesn't seem to be any logic in `Installer#install` that says otherwise.

That said, I'm not sure that my changes have caused the behaviour jmhodges is describing. I'll try to get to the bottom of it this weekend though.

**Comment by defunkt** [comment]
It used to not install meta_packages - see  http://github.com/defunkt/rip/commit/f029c292c46698a8f632af8e6397b2d176015c4c

**Comment by lazyatom** [comment]
Apologies for that - I must've accidentally removed that line when trying to get dependencies to work.

I believe that adding it back in fixes this, and #70; see [here](http://github.com/lazyatom/rip/commit/e585373101546a708384c31029abd977186a7a6b)

**Comment by jmhodges** [comment]
+1 on that fix.

```
 →  rip install deps.rip 
 Successfully installed sinatra (3b992ad)
 Successfully installed cassandra_object (917c263)

 →  echo 'erubis' >> deps.rip 

 →  rip install deps.rip 
 rip: already installed sinatra (3b992ad)
 rip: already installed cassandra_object (917c263)
 Successfully installed abstract (1.0.0)
 Successfully installed erubis (2.6.5)
```

**Comment by defunkt** [comment]
Thanks for the fix - merged and pushed!
