### ISSUE TITLE
Add `ui` helper and associated classes

### ISSUE THREAD

**Issue by defunkt** [defunkt/rip#7]
`puts` => `ui.puts`

`abort` => `ui.abort`

**Comment by defunkt** [comment]
This'll clear out all the crap in the test output and let us actually run the tests without nasty `aborts` ruining our fun.

**Comment by nakajima** [comment]
See nakajima/rip@b9a688d62f947cebbc18a29cecb2be2f39543105 through nakajima/rip@7dfeab1ef57d7b7abe8562586dda88b3bb324320.

**Comment by defunkt** [comment]
Great, merged in.
