### ISSUE TITLE
Libraries conflicting with themselves

### ISSUE THREAD

**Issue by defunkt** [defunkt/rip#70]
http://gist.github.com/172556

**Comment by defunkt** [comment]
Disaster averted - installing from Git works. This appears gem related.

**Comment by lazyatom** [comment]
I'll look into this

**Comment by lazyatom** [comment]
I believe this is fixed [here](http://github.com/lazyatom/rip/commit/e585373101546a708384c31029abd977186a7a6b)

**Comment by jmhodges** [comment]
+1 to this patch, too.

**Comment by defunkt** [comment]
Brilliant! Merged in, thanks.
