### ISSUE TITLE
Ignore blank lines in ripfiles

### ISSUE THREAD

**Issue by josh** [defunkt/rip#71]
Rip::RipfilePackage#dependencies! doesn't skip over blank lines. So it tries to call Package.for(nil, nil) which then blows up because it is expecting a string.

I feel like a total n00b because I couldn't figure out how to write a failing test for this.

Patch: ignore blank lines in ripfiles
http://github.com/josh/rip/commit/649da95aafe7807c98ac8a88c7269971b9c84252

**Comment by josh** [comment]
My bad. I had a stray tab on the last line of my deps file. Totally works fine if the last line is completely blank which is all I care about.

Dunno if adding this extra code is worth it.

**Comment by lazyatom** [comment]
I think 'not blowing up' would be the right behaviour here, so adding the check in seems good to me. Rip should at least be able to gracefully skip over malformed contents of ripfiles.

As a tangent, if we're checking for lines to ignore, we could allow some form of comment line in `.rip` files too - any line starting with `#`, maybe? I don't know if that's useful at all, but it's certainly a possibility.

**Comment by josh** [comment]
Great idea. Supporting comments would be really useful.

**Comment by josh** [comment]
Patch: ignore comments in ripfiles
http://github.com/josh/rip/commit/3a552f3449c6ba77670729839b9a7660bc17a4a7

**Comment by josh** [comment]
http://github.com/defunkt/rip/commit/3a552f3449c6ba77670729839b9a7660bc17a4a7
