### ISSUE TITLE
Safely remove package directories

### ISSUE THREAD

**Issue by josh** [defunkt/rip#72]
Some packages share or overlap directories, such as rack, rack-contrib, rack-cache, rack-test. Installing any of these packages in any order works fine. But if you install rack and rack-contrib. Uninstalling rack will wipe all the files under rack/contrib/\* as well.

This patch removes all the package files first, then cleans up the empty directories.

Patch: safely remove package directories
http://github.com/josh/rip/commit/308e9df23721d3f28ef54f33759218374c0d748a

**Comment by lazyatom** [comment]
This patch looks good based on my informal local testing. Really nice work.

**Comment by josh** [comment]
http://github.com/defunkt/rip/commit/308e9df23721d3f28ef54f33759218374c0d748a
