### ISSUE TITLE
Files outside of `bin` and `lib` are not copied

### ISSUE THREAD

**Issue by lazyatom** [defunkt/rip#75]
I'm not sure if this is a bug, per-se, but it's worth thinking about. I have a gem (vanilla) that has a couple of template configuration files in the root of it's directory structure:

```
vanilla
  |- bin/
      |- vanilla
  |- lib/
  |- config.ru
  |- config.example.yml
```

The `vanilla` binary expects to be able to find and copy those files to set up a vanilla installation on the local machine, but because Rip only cares about `bin` and `lib`, those files are left behind in the cache.

Obviously, one solution is for me to just move the files into `lib`, but I wonder if it's worth thinking about how to handle this in general? It seems like we couldn't always copy every file, because then `README` would almost always cause a `FileConflict`, but it also feels like this kind of stuff doesn't belong in `lib`.

Rip could copy the contents of any directory, but then we'd have to explicitly exclude things like `test` and `spec` and `features` and so on, so I'm not sure if that will work well either.

Anyone got any thoughts?

**Comment by lenary** [comment]
This is a very good point. I know i had to vendor a library to get bleeding-edge features which hadn't hit the gem release yet, so if you're not copying in my vendor directory, you're going to break my gem.

I think certainly the vendor directory should be copied in, and certainly others, like sinatra apps made as a gem require views and public to be copied in as well.

**Comment by ambethia** [comment]
If I understand the best practice for rip, the things you vendored would go in your deps.rip file.

```
git://example.org/some_lib.git d46e3fa0
```

And rip will install it along side your lib code.

**Comment by lenary** [comment]
Sounds like a good idea, but I can perhaps see an issue. Can two ruby scripts, both of which run at the same time on the same machine (same user and all) use different ripenvs. This would be advantageous if they need two different versions of the same library. 

If this is not possible then my point still stands

**Comment by defunkt** [comment]
"Can two ruby scripts, both of which run at the same time on the same machine (same user and all) use different ripenvs."

Yes, just use the `rip ruby` command.

**Comment by lenary** [comment]
That's what happens from not touching a proper (ruby-running) computer of your own for a month and a half.

This means I am now of the opinion that only copying bin and lib is probably good. It should also keep gems and repositories mildly organised rather than the disorganisation seen in a few libraries or applications (this isn't writing off all gems/libraries with stuff not in bin or lib, just saying you probably need a better reason than "I feel like it")
