### ISSUE TITLE
rip env issue with ruby 1.9

### ISSUE THREAD

**Issue by ghost** [defunkt/rip#78]
In ruby 1.9, the instance_methods used by Rip::Env now returns an array of symbols. In order to make the rip env command work I converted the Rip::Env:commands to work with symbols.

<pre>
index 42e792d..3e0dc5c 100644
--- a/lib/rip/commands/core.rb
+++ b/lib/rip/commands/core.rb
@@ -27,7 +27,7 @@ module Rip
     x 'Commands for managing your ripenvs.'
     x 'Type rip env to see valid options.'
     def env(options = {}, command = nil, *args)
-      if command && Rip::Env.commands.include?(command)
+      if command && Rip::Env.commands.include?(command.to_sym)
         args.push(options)
         ui.puts 'ripenv: ' + Rip::Env.call(command, *args).to_s
       else
diff --git a/lib/rip/env.rb b/lib/rip/env.rb
index 8dabc40..e7e2122 100644
--- a/lib/rip/env.rb
+++ b/lib/rip/env.rb
@@ -5,7 +5,7 @@ module Rip
     PRIVATE_ENV =  /^(rip-|active)/i
 
     def commands
-      instance_methods - %w( call active_dir commands ui validate_ripenv )
+      instance_methods - [:call, :active_dir, :commands, :ui, :validate_ripenv]
     end
 
     x 'Create the SOURCE environment.'
</pre>

**Comment by rcrowley** [comment]
This patch gets Rip closer to working under 1.9 for me.  I don't quite understand the use of `Enumerable#any?` at lib/rip/sh/gem.rb, line 7 but it's pretty clearly breaking under ruby-1.9.1-p243:

```
(master) root@devbox:~# rip install sinatra
undefined method `any?' for "/opt/ruby-1.9.1-p243/bin/gem":String
rip: install failed
-> undefined method `any?' for "/opt/ruby-1.9.1-p243/bin/gem":String
(master) root@devbox:~#
```

**Comment by defunkt** [comment]
This should be solved in the upcoming Rip 2. Thanks!
