### ISSUE TITLE
add reflog

### ISSUE THREAD

**Issue by defunkt** [defunkt/rip#8]
Something similar to `git reflog` that records every action you take in Rip.

**Comment by amerine** [comment]
I have something basic working over at amerine/rip@a2aff2181792b52b30a70b2ae736348aa3627e2d

**Comment by amerine** [comment]
Now I just need to work on giving a use the ability to traverse back and forth through the history somehow.

**Comment by defunkt** [comment]
Any chance you could make this into a Rip plugin so we can play with it before including it in core?
