### ISSUE TITLE
`gem install rip` (without sudo) fails [OS X 10.6]

### ISSUE THREAD

**Issue by pvande** [defunkt/rip#82]
The primary reason for the failure appears to be related to attempting to install to `/usr/bin`, ignoring RubyGems' `--bindir` flag.

One hypothesized solution might be to allow RubyGems to install the `lib` and `bin`, and then invoke a setup routine that handles _only_ infrastructure setup.  I may look into this approach, if I find time.

**Comment by defunkt** [comment]
The approach you describe is how rip2 (now `master`) works. Sorry about that - once rip2 is ready it should behave better.
