### ISSUE TITLE
`gem dependency`'s -v flag is busted

### ISSUE THREAD

**Issue by defunkt** [defunkt/rip#93]
Today I released Resque 1.8.1 and noticed this command fails: 

`gem dependency --pipe -r /^resque$/ -v 1.8.0`

Seems the `-v` is ignored. Maybe a problem with [gem dependency](http://github.com/jbarnette/rubygems/blob/master/lib/rubygems/commands/dependency_command.rb), will have to check it out.

**Comment by josh** [comment]
rip is sane, rubygems 1.3.6 is broken.

I'm running 1.3.7.pre.1 which has the fix. You could also downgrade to 1.3.5 or use RPG :P
