### ISSUE TITLE
rip-exec doesn't work with dash(1)

### ISSUE THREAD

**Issue by defunkt** [defunkt/rip#99]
```
$ rip exec system rip list
eval: 1: Bad substitution
```

**Comment by rtomayko** [comment]
I think this is due to the regular expression substitutions output from `rip-config`:

```
RUBYLIB="$RIPDIR/boom/lib:${RUBYLIB/$RIPDIR\/active\/lib}"
PATH="$RIPDIR/boom/bin:${PATH/$RIPDIR\/active\/bin}"
```

Those are bash-only.

They're not needed in the `rip-exec` case. It might be best to have a `rip-exec` mode where it outputs the expanded `RUBYLIB` and `PATH` values.

**Comment by defunkt** [comment]
Okay, then I think this is a larger issue of bash vs sh and which rip should support.

Given the Ruby requirement, I think we should target sh. Anything too complicated or powerful for sh can be done in Ruby, and anything we need to do in shell stays simple.

**Comment by rtomayko** [comment]
Nicely put. That's my take on using sh exactly.

**Comment by josh** [comment]
c8601f8f018ec501b834291c71a6d1d5b9b5ba1a
